### ISSUE TITLE
Method for comparing texts according to their soundex representations

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#10]
Original [issue 10](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=10) created by dkpro on 2013-06-10T08:49:36.000Z:

This would be a nice addition. In principle it also works with several other measures, e.g. GreedyStringTiling on sounds instead of tokens.

This could be further generalized to stems/lemmas etc.

**Comment by zesch** [comment]
We have a couple of those measures in algorithms-sound.
What was the idea beyond that?

**Comment by nicolaierbs** [comment]
Honestly, I don't recall. It definitely wasn't high priority.
