### ISSUE TITLE
Sentiment similarity

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#15]
Original [issue 15](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=15) created by dkpro on 2013-09-11T13:32:09.000Z:

Do we have a similarity measure that compares two texts on an 'emotional' level?

I would like to develop a measure that checks if a text is opinionated (could be as well the polarity) and returns a high similarity value if both texts are to the same extend opinionated.

**Comment by zesch** [comment]
I am not sure how this could be operationalized.
Do we have a use case for this?

**Comment by nicolaierbs** [comment]
It could be used for clustering comments in a forum according to their polarity. It could be operationalized by including a sentiment classifier.

**Comment by zesch** [comment]
ok, let's assume we have run a sentiment classifier and now have two documents, one with "++" sentiment and one with "-" sentiment. What should be the similarity?

If it is not document, but aspect-based sentiment, we could compare if the aspects agree, but still I am  not sure what the similarity computation could do beyond trivial "is it the same sentiment" level.
However, I probably lack imagination regarding this :)

**Comment by nicolaierbs** [comment]
Well, it was supposed to be a simple solution and I don't believe it's needed any more. Let's close it and wait if everyone is going to need in the future.
