### ISSUE TITLE
Change groupId

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#27]
Original [issue 27](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=27) created by dkpro on 2014-03-31T09:10:17.000Z:

The groupId was truncated along with the artifactId. However, the groupId should have remained fully-qualified. We should changed it back to

&lt;groupId&gt;de.tudarmstadt.ukp.dkpro.similarity&lt;/groupId&gt;

**Comment by reckart** [comment]
Should now be `org.dkpro.similarity` - and the artifacts should be `dkpro-similarity-XXX`.

**Comment by reckart** [comment]
I have changed the artifactId and groupIds everywhere. The command line/Jenkins build is also cool, but the build in Eclipse for me has various projects with exclamation marks. So far, I couldn't find out why or how to fix it - I even did a fresh clone and reimport into Eclipse.

Does anybody else see these exclamation marks in Eclipse on the latest DKPro Similarity?

**Comment by zesch** [comment]
Everything works fine here with a fresh clone/import.

**Comment by reckart** [comment]
Ok, then let's close this. Thanks for testing!
