### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#28]
Original [issue 28](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=28) created by dkpro on 2014-05-02T13:51:55.000Z:

Hi,

is there any plan or timetable about pushing the dkpro-similarity-asl library(s) to Maven Central.
I have to use this lib in an Maven central compliant framework and I need a compliant enviroment

Best regards
Thomas

**Comment by reckart** [comment]
How much of similarity would be "lost" if we only released the things that have no problematic dependencies?

**Comment by zesch** [comment]
Does "problematic" include third party uploads?
If yes, we would lose 3/4 of similarity (conservative estimate).

**Comment by reckart** [comment]
Yea, I though mainly about third-party uploads actually. Are there other kinds of problems?

**Comment by zesch** [comment]
IIRC DKPro LSR is also not on maven central yet.

**Comment by areese** [comment]
Is there a dependency tree that can be looked at as to what is preventing it from going to maven central?

@nschimme and I are interested in pulling from maven central:
So I don't have to mirror it and so we  don't end up taking your artifactory out on accident by pushing way too much traffic.

**Comment by reckart** [comment]
You can use Eclipse or the Maven dependency plugin to generate a tree. I don't think though that there is an option to tell you from which particular repository a dependency was pulled.

Mind that Maven Central could in theory also fail or be temporary unavailable. I would always recommend to run a mirroring proxy repository under your control if you heavily rely on Maven.

https://maven.apache.org/plugins/maven-dependency-plugin/

**Comment by reckart** [comment]
Sorry, actually this seems to be what you are looking for ;)

https://maven.apache.org/plugins/maven-dependency-plugin/list-repositories-mojo.html

**Comment by areese** [comment]
We mirror central.  :)  I'm just trying to avoid mirror sprawl, where I have a giant list of mirrors to manage.

What I'm asking is what dependencies prevent you from pushing to central.  That's what I'm curious about.

**Comment by reckart** [comment]
Ok, I just tried the "list-repositories" mojo, but it doesn't say which dependency comes from which repo - it only lists the repos used in a module.

So what you could try without hunting down each dependency individually is:

* start with a clean local repo
* check out the project you wish to analyze the dependencies (i.e. dkpro similarity)
* build it
* there should be `_remote.repositories` files now in your local repository - find all of them that do not contain the string "central"

Might work ;) Cannot try it currently.

**Comment by areese** [comment]
Thanks I'll work with @nschimme on this and see what we can come up with.  I appreciate the effort.

**Comment by reckart** [comment]
We should also fix the groupId/artifactId before deploying this on a proper repository: #27

**Comment by torbjornvatn** [comment]
Any ETA on when this could get pushed to Maven Central?

**Comment by nicolaierbs** [comment]
@torbjornvatn: I plan to work on the project after christmas, but it will be hard to estimate when we'll be finished.

**Comment by nicolaierbs** [comment]
Preparation of release started.
Opened issue for creating project at https://issues.sonatype.org/browse/OSSRH-19698

**Comment by nicolaierbs** [comment]
I analyzed the dependencies in DKPro Similarity and found only few, which are not on Maven Central.

* DKPro LSR is heavily used in two modules. The following dependencies are required: 
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource-asl:0.8.1
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource.graph-asl:0.8.1
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource.germanet-gpl:0.8.1
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource.wikipedia-asl:0.8.1
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource.wiktionary-asl:0.8.1
   * de.tudarmstadt.ukp.dkpro.lexsemresource:de.tudarmstadt.ukp.dkpro.lexsemresource.wordnet-asl:0.8.1
   * I removed these dependencies and deleted both LSR modules in DKPro Similarity.
* de.tudarmstadt.langtech.substituter.twsi is used in dkpro-similarity-algorithms-lexsub-gpl
   * I upgraded it to version 1.1 which is on Maven Central.
* hultiglib:hultiglib:1.1 is used in dkpro-similarity-algorithms-lexical-gpl
   * I removed the dependency and one class which makes use if it
* com.wcohen.ss:secondstring:20060615
   * I removed the dependency and removed the classes which make use of it.
   * This would be a candidate for a 3rd party upload
* I deleted the modules with experiments

I would propose to release the everything left to Maven Central. All modules using DKPro LSR will not be added and reintegrated after DKPro LSR has been replaced.

**Comment by reckart** [comment]
Hum, were the experiments not an essential part of DKPro Similarity? Why not exclude them from deployment instead of completely deleting them? Likewise for the modules that use LSR.

**Comment by nicolaierbs** [comment]
I agree. We can keep the deleted modules and exclude them from the release. Any other objections, or can I continue with the release to Maven Central?

**Comment by reckart** [comment]
Do you have license checking in place for ASL and GPL? 
Are NOTICE.txt files in place that explain where third party code and/or resources come from (if any)?
If you plan to release, I suggest you stop after you have staged the artifacts and ask us to review the staged artifacts before you promote them to Maven Central.

**Comment by nicolaierbs** [comment]
Richard, do you have any recommendation how to check licenses?

**Comment by reckart** [comment]
You can copy the respective configurations from DKPro Core:

* https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-asl/pom.xml#L550
* https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-gpl/pom.xml#L108

Place these in the corresponding ASL/GPL aggregator modules in DKPro Similarity.

The GPL check requires each module to contain a `.license-header.txt` file with the respective license text. Cf. such files in DKPro Core.

**Comment by nicolaierbs** [comment]
Does anyone know whether we can include a dependency with the University of Illinois/NCSA Open Source License (NCSA) in an ASL module? According to https://opensource.org/licenses/NCSA and http://directory.fsf.org/wiki/License:IllinoisNCSA it is non-copyleft and allows commercial use. It is definitely compatible to GPL, but I don't want to move it to GPL without any need.

**Comment by reckart** [comment]
Do you have a link to the software (not the license)?

NCSA is listed at ASF under similar to ALv2 (http://www.apache.org/legal/resolved.html#category-a) - so it's totally fine for us.

**Comment by nicolaierbs** [comment]
Sure. They recently moved to GitHub: https://github.com/TeamCohen/secondstring/

**Comment by nicolaierbs** [comment]
I just added the necessary plugins to the parent pom. Is there anything I should check, or can I go ahead and do the release?

**Comment by nicolaierbs** [comment]
Uploaded 3rd party dependencies to Maven Central (http://search.maven.org/#artifactdetails%7Ccom.wcohen%7Ccom.wcohen.secondstring%7C0.1%7Cjar)

**Comment by nicolaierbs** [comment]
DKPro Similarity 2.2.0 has been successfully released! Could you please review the artifacts (http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.dkpro.similarity%22) and comment if there are any problems.

**Comment by daxenberger** [comment]
great news! :)

**Comment by nicolaierbs** [comment]
Closing this issue. Please re-open if there are any difficulties using the version from Maven Central
