### ISSUE TITLE
Fix groupIds

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#33]
Original [issue 33](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=33) created by dkpro on 2014-09-12T09:57:21.000Z:

GroupIDs where are some point truncated to &quot;dkpro.similarity&quot;. These should go back to &quot;de.tudarmstadt.ukp.dkpro.core.similarity&quot; as the groupId prefix should correspond to a domain name.

**Comment by nicolaierbs** [comment]
Group Id is 'org.dkpro.similarity'
Is there any reason why this bug is still open?

**Comment by daxenberger** [comment]
dkpro still uses the old "de.tudarmstadt.ukp.dkpro..." style IDs. Only the parent has been renamed so far.
@reckart is it planned to change all IDs in the near future?

**Comment by zesch** [comment]
We have to start somewhere anyway :)

**Comment by reckart** [comment]
Actually, I thought that I had resolved this issue a while back... ah... looks like a duplicate of https://github.com/dkpro/dkpro-similarity/issues/27
