### ISSUE TITLE
Migration of wiki from Google Code to GitHub

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#42]
Dear all,

I've just migrated the wiki contents from Google Code to GitHub. You can find the new website here: https://dkpro.github.io/dkpro-similarity/

Please report any missing links or information in this issue. Feel free to suggest any improvements.

**Comment by chrisyeah** [comment]
Hi Nicolai,

your "Getting Started" guide suggests to use "dkpro.similarity" as groupId and "dkpro.similarity.algorithms.api-asl" as artifactId (as Maven dependency). But this artifact is missing.

**Comment by nicolaierbs** [comment]
Hi Chris,
thanks for pointing it out. Did you try to add it in your pom? DKPro Similarity is not yet on Maven central, so you need to check it out before adding it as artifact.

**Comment by reckart** [comment]
I think you can get it from the UKP OSS repository at http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-releases/ . 

See also: https://dkpro.github.io/dkpro-core/pages/setup-maven.html

**Comment by chrisyeah** [comment]
Thank you for your answers. @reckart your answer is working, too.
Greetings from Hof ;)

**Comment by reckart** [comment]
The migration is done with the final merge of the GPL code into the main repository.
