### ISSUE TITLE
Remove Google Code build jobs on Jenkins

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-similarity#43]
If/when they are no longer in use, please remove this project's Google Code build jobs on Jenkins:
* [DKPro Similarity ASL (Google Code)](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Similarity%20ASL%20(Google%20Code)/)
* [DKPro Similarity GPL (Google Code)](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Similarity%20GPL%20(Google%20Code)/)

**Comment by reckart** [comment]
Done.
