### ISSUE TITLE
getting started with dkpro-similarity is not really satisfying

### ISSUE THREAD

**Issue by helt** [dkpro/dkpro-similarity#48]
The gettings started guide on https://dkpro.github.io/dkpro-similarity/gettingstarted/ does not really gets up to the point, where it is clear to the reader (i.e. to *me*), how the code actually looks like, which is in the magic rectangle (the rect with the bold border...) 

(My guess is that i iterate over another Collection within an AnalysisEngine, but havent found much yet, i.e. in a `getNext(JCas cas) ` i have a loop which fetches other JCas objects)

Any hints would be appreciated.

![text_sim_uima_pipe](https://cloud.githubusercontent.com/assets/1732112/10777047/75a097d6-7d17-11e5-9fda-014a5003d2d8.png)

**Comment by zesch** [comment]
It depends a bit on what you are trying to achieve with DKPro Similarity.
Some code examples are here: https://dkpro.github.io/dkpro-similarity/

The getting started guide might be misnamed a bit, as it tries to show how to reproduce our SemEval 2013 results.

For examples how to use the different measures, I recommend a look in the unit tests.
