### ISSUE TITLE
Disabled links to DKPro Similarity documentation

### ISSUE THREAD

**Issue by pauljurczak** [dkpro/dkpro-similarity#50]
I'm trying to get to [DKPro Similarity documentation](https://dkpro.github.io/dkpro-similarity/documentation/) and both links under Reference Documentation are disabled. Is there any other place to get the documentation?

**Comment by zesch** [comment]
I am afraid that currently there is no other documentation than what you have already found.

**Comment by reckart** [comment]
Maybe we should comment out the unlinked documentation sections at the bottom for good measure or at least add links to the auto-generated API docs on Jenkins?

**Comment by reckart** [comment]
Unused documentation sections removed in 9225df2b06cad5bc333e5f5fdaaaf7218eea6278.
