### ISSUE TITLE
Different results for TokenPairDistanceMeasureTest and TokenPairOrderingMeasureTest

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#53]
I executed the following two tests both using Eclipse and the command 'mvn clean install' and the outcome turned out to be different. In Eclipse the test finished successfully, while they failed in the terminal.

Any clues?

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running dkpro.similarity.algorithms.structure.TokenPairDistanceMeasureTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec <<< FAILURE! - in dkpro.similarity.algorithms.structure.TokenPairDistanceMeasureTest
run(dkpro.similarity.algorithms.structure.TokenPairDistanceMeasureTest)  Time elapsed: 0.068 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0.755> but was:<0.6407693851706187>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:443)
	at org.junit.Assert.assertEquals(Assert.java:512)
	at dkpro.similarity.algorithms.structure.TokenPairDistanceMeasureTest.run(TokenPairDistanceMeasureTest.java:93)

Running dkpro.similarity.algorithms.structure.TokenPairOrderingMeasureTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in dkpro.similarity.algorithms.structure.TokenPairOrderingMeasureTest
run(dkpro.similarity.algorithms.structure.TokenPairOrderingMeasureTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0.928> but was:<0.18898223650461377>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:443)
	at org.junit.Assert.assertEquals(Assert.java:512)
	at dkpro.similarity.algorithms.structure.TokenPairOrderingMeasureTest.run(TokenPairOrderingMeasureTest.java:68)

Results :

Failed tests: 
  TokenPairDistanceMeasureTest.run:93 expected:<0.755> but was:<0.6407693851706187>
  TokenPairOrderingMeasureTest.run:68 expected:<0.928> but was:<0.18898223650461377>

**Comment by daxenberger** [comment]
Java versions?

**Comment by nicolaierbs** [comment]
You're right. I use Java 7 in Eclipse and Java 8 when directly using Maven.

I'll keep this issue open to investigate why different Java versions change results.

**Comment by reckart** [comment]
This is typically due to changes in iteration orders over hashmaps or hashsets. Mind that for these classes, the iteration order is undefined. Can typically be fixed by explicitly sorting or using the "linked" versions of these classes to iterate in insertion order.

**Comment by nicolaierbs** [comment]
Thanks Richard. Changing to linked version solved this issues.

**Comment by reckart** [comment]
Please assign milestones before or latest when closing issues.
