### ISSUE TITLE
Word embedding file for LSA similarity measure

### ISSUE THREAD

**Issue by vaskonov** [dkpro/dkpro-similarity#57]
Hello,

I am trying to use 	
`import org.dkpro.similarity.algorithms.sspace.LsaSimilarityMeasure;
`
however the routine requires the embedding file, like on the following test
`TextSimilarityMeasure lsa = new LsaSimilarityMeasure(new File("src/test/resources/model/test.sspace"));
`	
I wonder where I can download the full version of the required file.  

I appreciate your help.

**Comment by zesch** [comment]
At the moment, we don't provide any rebuild models.

The idea is that you build your own (fitted to your problem at hand) using
https://github.com/dkpro/dkpro-similarity/blob/master/dkpro-similarity-algorithms-sspace-gpl/src/main/java/org/dkpro/similarity/algorithms/sspace/util/LsaIndexer.java
