### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-similarity#64]
How about doing a 2.2.1 or 2.3.0 release? The 2.2.0 release does not include the "dkpro-similarity-algorithms-lsr-asl" module yet and I would like to have a release version of that one.

**Comment by reckart** [comment]
@zesch WDYT? Any objections or preferences regarding how to name the version?

**Comment by zesch** [comment]
No preferences regarding the name. There have been relatively few changes so 2.2.1 sounds fine.

However, can we actually release the lsr module?
AFAIR it depends on DKPro LSR which had some release problems the last time I looked.

**Comment by reckart** [comment]
Are these documented somewhere? I don't see a conspicuously looking issue in the DKPro LSR. The code I have here uses the 0.8.1 DKPro LSR release. I wasn't aware this was not on Maven Central yet.

**Comment by reckart** [comment]
Well, for the moment, it turns out I can fall back to DKPro Similarity 2.2.0 and exclude the LSR-based stuff... still... maybe I find some time to have a look at LSR...

**Comment by zesch** [comment]
I investigated this some weeks ago and nobody seems to remember. My guess would be that some of the many, many dependencies of LSR are also not on Maven Central ...

**Comment by reckart** [comment]
@zesch Made some updates to DKPro Similarity. Build looks good.

I also made some adjustments to DKPro LSR. In principle, I think we'd also be good for a new LSR release, but first I'd tend to do a DKPro Similarity 2.3.0 and leave the LSR update for a DKPro Sim 2.4.0.

Any further comments at this point?

**Comment by zesch** [comment]
No comments at this point. Great work. Thanks for spring cleaning :)
